### ISSUE TITLE
Can't find custom plugin

### ISSUE THREAD

**Issue by wyatt-troia-msft** [Gitii/PackedPrettier#5]
Thank you for this package. I use it as a post-build command to format a Swagger file.

I have a custom plugin that I'm trying to use, but prettier is unable to find it, despite my providing a `prettierrc.json` config file with a `"plugin-search-directory"` containing the directory that contains the custom plugin. This config file works when I run prettier normally, in a JavaScript project.

The error I get is this:
```
  [error] Cannot find module 'prettier-plugin-custom'
  [error] Require stack:
  [error] - C:\snapshot\node_modules\prettier\index.js
  [error] - C:\snapshot\node_modules\prettier\bin-prettier.js
C:\Users\me\EdgeZoneRP.csproj(10,1): error MSB3073: The command "dotnet pprettier --config C:\Users\me\Swagger\prettierrc.json --plugin-search-dir=C:\Users\me\Swagger --plugin prettier-plugin-arm --write C:\Users\me\swagger.json" exited with code 1.
```

I've tried to copy my plugin to `"C:\snapshot\node_modules"` (I assume this directory is part of the virtual filesystem your README refers to) right before calling `pprettier`, but get this error: `"The system cannot find the path specified."`

Could you please tell me if there is a current solution for this?

**Comment by wyatt-troia-msft** [comment]
Also, how do we figure out what to replace `"<NodeModulesPath>"` with?

**Comment by Gitii** [comment]
Hi @wyatt-troia-msft ,

I never tried to use external plugins.
I will look into it (on the weekend, maybe Friday). There might be a conflict and you're argument get's overwritten.

As for you're second question: 
This placeholder will be resolved internally/at runtime, you need to use it as is (the literal value).

**Comment by wyatt-troia-msft** [comment]
@Gitii Thank you. I really appreciate it.

**Comment by Gitii** [comment]
Hi @wyatt-troia-msft,

I looked into it and could successfully load external plugins, for example:
I installed [Prettier Toml Plugin](https://github.com/bd82/toml-tools/tree/master/packages/prettier-plugin-toml) and also installed `PackedPrettier`:
```
dotnet tool run pprettier --write ./_input.toml --plugin-search-dir=./node_modules --plugin=prettier-plugin-toml
```

As far as I understand, only calls to `C:\snapshot\node_modules` will be redirected (it's not a real folder).
Beside that, it's just a normal program with full access to the filesystem.
I can also confirm that none of your arguments will get overwritten by `PackedPrettier`.

In your sample output, there are two plugins mentioned: `prettier-plugin-custom` and `prettier-plugin-arm`
I get a similar error when I specify a none-existing plugin:
```
[error] Cannot find module 'prettier-plugin-toml2'
[error] Require stack:
[error] - /snapshot/node_modules/prettier/index.js
[error] - /snapshot/node_modules/prettier/bin-prettier.js
```

Could you please check if your plugin is in the plugin folder you specified (`--plugin-search-dir`) and `--plugin` is correct?

Best regards

**Comment by wyatt-troia-msft** [comment]
Hi @Gitii. Thanks for looking into it. Hm.

The plugin does exist in the plugin folder I specify. I just copied them over from a test JavaScript project, along with the config. In the JavaScript project, the plugin is recognized and used successfully when running prettier.

The plugin is not an NPM package, though. It's just a local file that I wrote. Would that make a difference? Would it be better if I made it into an NPM package?

**Comment by Gitii** [comment]
According to the documentation
```
Strings provided to plugins are ultimately passed to require(), so you can provide a module/package name, a path, or anything else require() takes. (pluginSearchDirs works the same way. That is, valid plugin paths that it finds are passed to require().)
```

everything should work, that can be loaded by `require`.
Can you @wyatt-troia-msft please try to use only `--plugin=<full path to file with or without extension>`?

My "plugin" is loaded:
```
dotnet tool run pprettier --write ./_input.toml --plugin=./plugin
[error] _input.toml: TypeError: Cannot read property 'comments' of undefined
[error]     at attachComments (/snapshot/node_modules/prettier/index.js:14500:27)
[error]     at coreFormat (/snapshot/node_modules/prettier/index.js:14535:23)
[error]     at formatWithCursor$1 (/snapshot/node_modules/prettier/index.js:14765:14)
[error]     at Object.formatWithCursor (/snapshot/node_modules/prettier/index.js:60959:12)
[error]     at format$1 (/snapshot/node_modules/prettier/bin-prettier.js:18001:21)
[error]     at Object.formatFiles$1 [as formatFiles] (/snapshot/node_modules/prettier/bin-prettier.js:18115:16)
[error]     at async main (/snapshot/node_modules/prettier/bin-prettier.js:20216:5)
[error]     at async Object.run (/snapshot/node_modules/prettier/bin-prettier.js:20159:5)
```

It still fails to parse but the plugin itself is loaded.

**Comment by wyatt-troia-msft** [comment]
Your suggestion worked! Providing `--plugin-search-dir` and `--plugin` caused an error, but only providing `--plugin` with the full path to the file (with or without the extension) - along with removing the `plugins` and `pluginSearchDirs` options from the prettier config file - worked. I didn't realize you could provide a file path to `--plugin`. Will have to pay more attention to the docs next time :)

Thank you!

**Comment by wyatt-troia-msft** [comment]
@Gitii FYI, my cloud builds failed because my custom plugin required the `prettier` module and couldn't find it. Locally I guess the build process was able to find a node_modules folder somewhere higher up in my file system that had prettier in it. I think I may just have to end up using `npm`. I think anyone who uses a plugin that isn't included in PackedPrettier will have to as well, right, since all plugins import from `prettier`? Please let me know if you can think of a solve, as I'd love not to have to use `npm` for this one task.

**Comment by Gitii** [comment]
@wyatt-troia-msft
You can load the bundled `prettier`, for example:
```
const {
  doc: {
    builders: { concat }
  }
} = require('/snapshot/node_modules/prettier')
```

**Comment by wyatt-troia-msft** [comment]
Thanks. I didn't realize I could access the bundled prettier. That worked.
